version: '3.8'
services:
  trpbot:
    build: .
    env_file:
    - .env
    depends_on:
    - mariadb
    command: ["./wait-for-it.sh", "mariadb:3306", "--", "python", "main.py"]
  
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=TerminationProtocol631!
      - MYSQL_DATABASE=trpbotdb
      - MYSQL_USER=trpbot
      - MYSQL_PASSWORD=trp4rocks
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - mariadb-data:/var/lib/mysql 
    ports:
    - "3306:3306"

volumes:
  mariadb-data: